In [1]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-71, -22,  84,   9,  55, -82])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.3], [4.4, 5.5]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.3000],
        [4.4000, 5.5000]])

In [4]:
zeros = torch.zeros((2, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones((3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
empty = torch.empty((2, 3))
empty

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
arrange = torch.arange(5)
arrange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
longspace = torch.logspace(-10, 10, steps=5)
longspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [11]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [12]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 8.0350,  0.8189, -7.2523], grad_fn=<SqueezeBackward4>)


In [13]:
import torch.nn.functional as F

tensor1 = torch.tensor([1., 2., 3.])

softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [14]:
vocab_size = 80
embed_dim = 6
embedding = nn.Embedding(vocab_size, embed_dim)

input_indices = torch.LongTensor([1, 5, 3, 2])
embedded = embedding(input_indices)
print(embedded.shape)
print(embedded)

torch.Size([4, 6])
tensor([[-0.4897, -0.0807, -1.0339,  0.7757,  0.2620, -1.3267],
        [ 0.1243, -0.4492, -1.3731, -1.2246,  1.6462,  0.9252],
        [-0.5709,  0.4011,  0.4630, -1.7417,  1.8716, -0.1143],
        [ 1.0998,  0.8404, -1.1537, -0.5057, -0.9671, -0.8230]],
       grad_fn=<EmbeddingBackward0>)


In [15]:
a = torch.tensor([[1,2], [3,4], [5,6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
a @ b

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [16]:
int_64 = torch.randint(1, (3, 2)).float()
float_32 = torch.rand(2, 3)
result = torch.matmul(int_64, float_32)
result

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])