In [20]:
import torch
import torch.nn as nn

In [21]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 20, -42,  51,  43, -56,  80])

In [22]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.3], [4.4, 5.5]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.3000],
        [4.4000, 5.5000]])

In [23]:
zeros = torch.zeros((2, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [24]:
ones = torch.ones((3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
empty = torch.empty((2, 3))
empty

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [26]:
arrange = torch.arange(5)
arrange

tensor([0, 1, 2, 3, 4])

In [27]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [28]:
longspace = torch.logspace(-10, 10, steps=5)
longspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [29]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [30]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [31]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 0.0853, -1.4312, 11.0944], grad_fn=<SqueezeBackward4>)


In [32]:
import torch.nn.functional as F

tensor1 = torch.tensor([1., 2., 3.])

softmax_output = F.softmax(tensor1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [33]:
vocab_size = 80
embed_dim = 6
embedding = nn.Embedding(vocab_size, embed_dim)

input_indices = torch.LongTensor([1, 5, 3, 2])
embedded = embedding(input_indices)
print(embedded.shape)
print(embedded)

torch.Size([4, 6])
tensor([[-0.1139,  0.3512, -1.0416,  0.4769,  1.0475,  2.4135],
        [-0.1602, -0.5747, -0.6733, -1.0545, -1.0619,  0.8293],
        [-0.9118,  0.0419,  0.2383,  0.4240,  2.2267,  0.9288],
        [-0.4221, -0.0685, -1.4150,  0.9035,  0.8593, -0.4148]],
       grad_fn=<EmbeddingBackward0>)


In [34]:
a = torch.tensor([[1,2], [3,4], [5,6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
a @ b

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [35]:
int_64 = torch.randint(1, (3, 2)).float()
float_32 = torch.rand(2, 3)
result = torch.matmul(int_64, float_32)
result

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [36]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x, y, z)
print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])


In [42]:
x = torch.tensor([1.0], dtype=torch.float32)
y = torch.tanh(x)
y

tensor([0.7616])

In [ ]:
my