In [1]:
import torch

In [3]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 34, -46, -11, -12,  88, -63])

In [4]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.3], [4.4, 5.5]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.3000],
        [4.4000, 5.5000]])

In [5]:
zeros = torch.zeros((2, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones((3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
empty = torch.empty((2, 3))
empty

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
arrange = torch.arange(5)
arrange

tensor([0, 1, 2, 3, 4])

In [10]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [11]:
longspace = torch.logspace(-10, 10, steps=5)
longspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [12]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])